### 0) 필요 패키지 임포트

In [1]:
import pandas as pd
import numpy as np

#### 1) 시리즈(Series)

In [2]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
 index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [3]:
s.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [4]:
s.values

array([9904312, 3448737, 2890451, 2466052], dtype=int64)

In [5]:
pd.Series(range(10, 14))

0    10
1    11
2    12
3    13
dtype: int64

In [8]:
s.name = '인구'
s.index.name = '도시'
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

#### 1-2) 시리즈 연산

In [9]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

#### 1-3) 시리즈 인덱싱

In [14]:
s[1], s['부산']

(3448737, 3448737)

In [15]:
s[3], s['대구']

(2466052, 2466052)

In [16]:
s[[0, 3, 1]]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [17]:
s[['서울', '대구','부산']]

도시
서울    9904312
대구    2466052
부산    3448737
Name: 인구, dtype: int64

In [19]:
s[(250e4 < s) & (s < 500e4)]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [20]:
s[1:3]

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [21]:
s['부산':'대구']

도시
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [23]:
s0 = pd.Series(range(3), index=['a','b','c'])
s0

a    0
b    1
c    2
dtype: int64

In [24]:
s0.a

0

In [25]:
s0.b

1

####  1-4) 시리즈와 딕셔너리 자료형

In [26]:
'서울' in s

True

In [27]:
'대전' in s

False

In [28]:
for k, v in s.items():
    print('%s = %d' % (k, v))

서울 = 9904312
부산 = 3448737
인천 = 2890451
대구 = 2466052


In [29]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158})
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [30]:
s2[1]

3393191

In [31]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
 index=["부산", "서울", "인천", "대전"])
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

#### 1-5) 인덱스 기반 연산

In [34]:
s, s2

(도시
 서울    9904312
 부산    3448737
 인천    2890451
 대구    2466052
 Name: 인구, dtype: int64,
 부산    3393191
 서울    9631482
 인천    2632035
 대전    1490158
 dtype: int64)

In [33]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [35]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [36]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [37]:
rs = (s-s2) / s2 *100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

#### 1-6) 데이터의 갱신, 추가, 삭제

In [39]:
rs['부산'] = 1.63
rs

부산    1.630000
서울    2.832690
인천    9.818107
dtype: float64

In [40]:
rs['대구'] = 1.41
rs

부산    1.630000
서울    2.832690
인천    9.818107
대구    1.410000
dtype: float64

In [41]:
del rs['서울']
rs

부산    1.630000
인천    9.818107
대구    1.410000
dtype: float64

### 2) 데이터프레임(DataFrame)

In [42]:
values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']
df = pd.DataFrame(values, index=index, columns=columns)
print('데이터프레임 출력 :')
print('-'*18)
print(df)


데이터프레임 출력 :
------------------
       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9


In [43]:
df1 = pd.DataFrame(values, columns=columns)
print(df1)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [45]:
print(df.index)
print(df.columns)
print(df.values)

Index(['one', 'two', 'three'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 3) 데이터프레임의 생성

#### 3-1) 데이터프레임

In [60]:
data = [
 ['1000', 'Steve', 90.72],
 ['1001', 'James', 78.09],
 ['1002', 'Doyeon', 98.43],
 ['1003', 'Jane', 64.19],
 ['1004', 'Pilwoong', 81.30],
 ['1005', 'Tony', 99.14],
]
df = pd.DataFrame(data)
print(df)


      0         1      2
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [61]:
df = pd.DataFrame(data, columns=['학번', '이름', '점수'])
print(df)

     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.09
2  1002    Doyeon  98.43
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14


In [62]:
data = {
 "2015": [9904312, 3448737, 2890451, 2466052],
 "2010": [9631482, 3393191, 2632035, 2431774],
 "2005": [9762546, 3512547, 2517680, 2456016],
 "2000": [9853972, 3655437, 2466338, 2473990],
 "지역": ["수도권", "경상권", "수도권", "경상권"],
 "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
columns = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]
index = ["서울", "부산", "인천", "대구"]
df = pd.DataFrame(data, index=index, columns=columns)
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [63]:
df.values

array([['수도권', 9904312, 9631482, 9762546, 9853972, 0.0283],
       ['경상권', 3448737, 3393191, 3512547, 3655437, 0.0163],
       ['수도권', 2890451, 2632035, 2517680, 2466338, 0.0982],
       ['경상권', 2466052, 2431774, 2456016, 2473990, 0.0141]], dtype=object)

In [64]:
df.columns

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [65]:
df.index

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [66]:
df.T

서울       부산       인천       대구
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

#### 3-2) 열 데이터의 갱신, 추가, 삭제

In [67]:
df["2010-2015 증가율"] = df["2010-2015 증가율"] * 100
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83
부산  경상권  3448737  3393191  3512547  3655437           1.63
인천  수도권  2890451  2632035  2517680  2466338           9.82
대구  경상권  2466052  2431774  2456016  2473990           1.41

In [68]:
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [69]:
df["2005-2010 증가율"] = ((df["2010"] - df["2005"]) / df["2005"] * 100).round(2)
df

지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972           2.83          -1.34
부산  경상권  3448737  3393191  3512547  3655437           1.63          -3.40
인천  수도권  2890451  2632035  2517680  2466338           9.82           4.54
대구  경상권  2466052  2431774  2456016  2473990           1.41          -0.99

In [70]:
del df['2010-2015 증가율']
df

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54
대구  경상권  2466052  2431774  2456016  2473990          -0.99

#### 3-3) 열 인덱싱

In [71]:
df['지역']

서울    수도권
부산    경상권
인천    수도권
대구    경상권
Name: 지역, dtype: object

In [72]:
df[['2010', '2015']]

2010     2015
서울  9631482  9904312
부산  3393191  3448737
인천  2632035  2890451
대구  2431774  2466052

In [75]:
df[['2010']]

2010
서울  9631482
부산  3393191
인천  2632035
대구  2431774

In [76]:
type(df[['2010']])

pandas.core.frame.DataFrame

In [78]:
type(df['2010'])

pandas.core.series.Series

In [80]:
df2 = pd.DataFrame(np.arange(12).reshape(3,4))
df2

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [81]:
df2[2]

0     2
1     6
2    10
Name: 2, dtype: int32

In [83]:
df2[[1,2]]

1   2
0  1   2
1  5   6
2  9  10

#### 3-4) 행 인덱싱

In [84]:
df[:1]

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972          -1.34

In [85]:
df[1:2]

지역     2015     2010     2005     2000  2005-2010 증가율
부산  경상권  3448737  3393191  3512547  3655437           -3.4

In [86]:
df[1:3]

지역     2015     2010     2005     2000  2005-2010 증가율
부산  경상권  3448737  3393191  3512547  3655437          -3.40
인천  수도권  2890451  2632035  2517680  2466338           4.54

In [87]:
df['서울':'부산']

지역     2015     2010     2005     2000  2005-2010 증가율
서울  수도권  9904312  9631482  9762546  9853972          -1.34
부산  경상권  3448737  3393191  3512547  3655437          -3.40

In [88]:
df['2015']['서울']

9904312

### #2 연습문제

In [221]:
data = {
 "국어": [80, 90, 70, 30],
 "영어": [90, 70, 60, 40],
 "수학": [90, 60, 80, 70],
}
columns = ["국어", "영어", "수학"]
index = ["춘향", "몽룡", "향단", "방자"]
df = pd.DataFrame(data, index=index, columns=columns)

In [222]:
df

국어  영어  수학
춘향  80  90  90
몽룡  90  70  60
향단  70  60  80
방자  30  40  70

In [223]:
df['수학']

춘향    90
몽룡    60
향단    80
방자    70
Name: 수학, dtype: int64

In [224]:
df[['국어','영어']]

국어  영어
춘향  80  90
몽룡  90  70
향단  70  60
방자  30  40

In [225]:
df['평균'] = round(((df['국어'] + df['영어'] + df['수학'])/3),2)
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [226]:
df

국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  40  70  46.67

In [227]:
df['영어']['방자'] = 80
df

C:\Users\user\AppData\Local\Temp\ipykernel_4152\4202567067.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['영어']['방자'] = 80


국어  영어  수학     평균
춘향  80  90  90  86.67
몽룡  90  70  60  73.33
향단  70  60  80  70.00
방자  30  80  70  46.67

In [228]:
df['춘향':'춘향']

국어  영어  수학     평균
춘향  80  90  90  86.67

In [229]:
df.T['향단']

국어    70.0
영어    60.0
수학    80.0
평균    70.0
Name: 향단, dtype: float64

### 5) 외부 데이터 읽기

In [117]:
df = pd.read_csv('RegularSeasonCompactResults.csv')
print(df)

        Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0         1985      20     1228      81     1328      64    N      0
1         1985      25     1106      77     1354      70    H      0
2         1985      25     1112      63     1223      56    H      0
3         1985      25     1165      70     1432      54    H      0
4         1985      25     1192      86     1447      74    H      0
...        ...     ...      ...     ...      ...     ...  ...    ...
156084    2018     132     1153      56     1222      55    N      0
156085    2018     132     1172      58     1348      57    N      0
156086    2018     132     1209      74     1426      61    N      0
156087    2018     132     1246      77     1397      72    N      0
156088    2018     132     1335      68     1217      65    N      0

[156089 rows x 8 columns]


#### 5-1) CSV 파일 입력 및 %%write 명령

In [118]:
%%writefile sample1.csv
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample1.csv


In [119]:
pd.read_csv('sample1.csv')

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [128]:
%%writefile sample2.csv
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample2.csv


In [129]:
pd.read_csv('sample2.csv', names = ['c1', 'c2','c3'])

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [130]:
pd.read_csv('sample1.csv', index_col ='c1')

c2      c3
c1              
1   1.11     one
2   2.22     two
3   3.33   three

In [133]:
%%writefile sample4.txt
파일 제목: sample4.txt
데이터 포맷의 설명:
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample4.txt


In [134]:
pd.read_csv('sample4.txt', skiprows=[0,1])

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [135]:
%%writefile sample5.csv
c1, c2, c3
1, 1.11, one
2, , two
누락, 3.33, three

Writing sample5.csv


In [136]:
df = pd.read_csv('sample5.csv', na_values=['누락'])
df

c1     c2      c3
0  1.0   1.11     one
1  2.0            two
2  NaN   3.33   three

In [137]:
df = pd.read_csv('sample5.csv', na_values=['누락', ' '])
df

c1    c2      c3
0  1.0  1.11     one
1  2.0   NaN     two
2  NaN  3.33   three

In [138]:
df.to_csv('sample6.csv')

In [139]:
!type sample6.csv

,c1, c2, c3
0,1.0,1.11, one
1,2.0,, two
2,,3.33, three


In [142]:
df = pd.read_csv("https://raw.githubusercontent.com/datascienceschool/docker_rpython/master/data/titanic.csv")

### 6. 데이터프레임 고급 인덱싱

#### 6-1) loc 인덱서

In [149]:
df = pd.DataFrame(np.arange(10,22).reshape(3,4),
 index=["a", "b", "c"],
 columns=["A", "B", "C", "D"])
df


A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [150]:
df.loc['a']

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [151]:
df.loc['b':'c']

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [152]:
df['b':'c']

A   B   C   D
b  14  15  16  17
c  18  19  20  21

In [153]:
df.A > 15

a    False
b    False
c     True
Name: A, dtype: bool

In [154]:
df.loc[df.A > 15]

A   B   C   D
c  18  19  20  21

In [155]:
df2 = pd.DataFrame(np.arange(10, 26).reshape(4, 4), columns=["A", "B", "C", "D"])
df2

A   B   C   D
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [156]:
df2.loc[1:2]

A   B   C   D
1  14  15  16  17
2  18  19  20  21

In [157]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
 index=["a", "b", "c"],
 columns=["A", "B", "C", "D"])
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [158]:
df.loc['a', 'A']

10

In [159]:
df.loc['b','A']

14

In [161]:
df.loc['a',:]

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [162]:
df.loc[['a','b'],['B','D']]

B   D
a  11  13
b  15  17

In [163]:
df.loc[df.A > 10, ['C','D']]

C   D
b  16  17
c  20  21

#### 6-2) 인덱서

In [164]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
 index=["a", "b", "c"],
 columns=["A", "B", "C", "D"])
df


A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [165]:
df.iloc[0,1]

11

In [166]:
df.iloc[:2, 2]

a    12
b    16
Name: C, dtype: int32

In [167]:
df.iloc[0,-2:]

C    12
D    13
Name: a, dtype: int32

In [168]:
df.iloc[2:3, 1:3]

B   C
c  19  20

In [169]:
df.iloc[-1]

A    18
B    19
C    20
D    21
Name: c, dtype: int32

#### 7. 데이터프레임의 데이터 조작

#### 7-1) 데이터 갯수 세기

In [179]:
s= pd.Series(range(10))
s[3] = np.nan
s

0    0.0
1    1.0
2    2.0
3    NaN
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
dtype: float64

In [181]:
s.count()

9

In [184]:
np.random.seed(2)
df = pd.DataFrame(np.random.randint(5, size=(4,4)), dtype=float)
df.iloc[2,3] = np.nan
df

0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [185]:
df.count()

0    4
1    4
2    4
3    3
dtype: int64

#### 7-2) 카테고리 값 세기

In [187]:
np.random.seed(1)
s2 =pd.Series(np.random.randint(6, size =100))
s2.tail()

95    4
96    5
97    2
98    4
99    3
dtype: int32

In [188]:
s2.value_counts()

1    22
0    18
4    17
5    16
3    14
2    13
dtype: int64

In [190]:
df[0].value_counts()

3.0    2
0.0    1
4.0    1
Name: 0, dtype: int64

#### 7-3) 정렬

In [191]:
s2.value_counts().sort_index()

0    18
1    22
2    13
3    14
4    17
5    16
dtype: int64

In [192]:
s.sort_values()

0    0.0
1    1.0
2    2.0
4    4.0
5    5.0
6    6.0
7    7.0
8    8.0
9    9.0
3    NaN
dtype: float64

In [193]:
s.sort_values(ascending= False)

9    9.0
8    8.0
7    7.0
6    6.0
5    5.0
4    4.0
2    2.0
1    1.0
0    0.0
3    NaN
dtype: float64

In [194]:
df.sort_values(by=1)

0    1    2    3
0  0.0  0.0  3.0  2.0
1  3.0  0.0  2.0  1.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

In [195]:
df.sort_values(by=[1,2])

0    1    2    3
1  3.0  0.0  2.0  1.0
0  0.0  0.0  3.0  2.0
2  3.0  2.0  4.0  NaN
3  4.0  3.0  4.0  2.0

#### 7-4) 행/열 합계

In [196]:
np.random.seed(1)
df2 = pd.DataFrame(np.random.randint(10, size=(4,8)))
df2

0  1  2  3  4  5  6  7
0  5  8  9  5  0  0  1  7
1  6  9  2  4  5  2  4  2
2  4  7  7  9  1  7  0  6
3  9  9  7  6  9  1  0  1

In [197]:
df2.sum(axis=1)

0    35
1    34
2    41
3    42
dtype: int64

In [198]:
df2['RowSum']= df2.sum(axis=1)
df2

0  1  2  3  4  5  6  7  RowSum
0  5  8  9  5  0  0  1  7      35
1  6  9  2  4  5  2  4  2      34
2  4  7  7  9  1  7  0  6      41
3  9  9  7  6  9  1  0  1      42

In [199]:
df2.sum()

0          24
1          33
2          25
3          24
4          15
5          10
6           5
7          16
RowSum    152
dtype: int64

In [201]:
df3 = pd.DataFrame({
 'A': [1, 3, 4, 3, 4],
 'B': [2, 3, 1, 2, 3],
 'C': [1, 5, 2, 4, 4]
})
df3

A  B  C
0  1  2  1
1  3  3  5
2  4  1  2
3  3  2  4
4  4  3  4

In [202]:
df3.apply(lambda x: x.max() -x.min())

A    3
B    2
C    4
dtype: int64

In [204]:
df3.apply(lambda x : x.max() - x.min(), axis=1)

0    1
1    2
2    3
3    2
4    1
dtype: int64

#### 7-8) fillna 메서드

In [208]:
df3.apply(pd.value_counts).fillna(0.0)

A    B    C
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

In [209]:
df.apply(pd.value_counts).fillna(0).astype(int)

0  1  2  3
0.0  1  2  0  0
1.0  0  0  0  1
2.0  0  1  1  2
3.0  2  1  1  0
4.0  1  0  2  0

#### 7-8) 실수 값을 카테고리 값으로 변환

In [211]:
ages = [0, 2, 10, 21, 23, 37, 31, 61, 20, 41, 32, 101]

In [213]:
bins = [1, 20, 30, 50, 70, 100]
labels = ["미성년자", "청년", "중년", "장년", "노년"]
cats = pd.cut(ages, bins, labels=labels)
cats

[NaN, '미성년자', '미성년자', '청년', '청년', ..., '장년', '미성년자', '중년', '중년', NaN]
Length: 12
Categories (5, object): ['미성년자' < '청년' < '중년' < '장년' < '노년']

In [214]:
type(cats)

pandas.core.arrays.categorical.Categorical

In [215]:
cats.categories

Index(['미성년자', '청년', '중년', '장년', '노년'], dtype='object')

In [216]:
cats.codes

array([-1,  0,  0,  1,  1,  2,  2,  3,  0,  2,  2, -1], dtype=int8)

In [218]:
df4 = pd.DataFrame(ages, columns=['ages'])
df4['age_cat'] = pd.cut(df4.ages, bins, labels=labels)
df4

ages age_cat
0      0     NaN
1      2    미성년자
2     10    미성년자
3     21      청년
4     23      청년
5     37      중년
6     31      중년
7     61      장년
8     20    미성년자
9     41      중년
10    32      중년
11   101     NaN

In [219]:
df4.age_cat.astype(str) + df4.ages.astype(str)

0       nan0
1      미성년자2
2     미성년자10
3       청년21
4       청년23
5       중년37
6       중년31
7       장년61
8     미성년자20
9       중년41
10      중년32
11    nan101
dtype: object

In [251]:
data = np.random.randn(1000)
cats = pd.qcut(data, 4, labels=["Q1", "Q2", "Q3", "Q4"])
cats

['Q3', 'Q1', 'Q2', 'Q2', 'Q1', ..., 'Q2', 'Q2', 'Q3', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [253]:
pd.value_counts(cats)

Q1    250
Q2    250
Q3    250
Q4    250
dtype: int64

### 8) 그룹분석

In [230]:
np.random.seed(0)
df2 = pd.DataFrame({
 'key1': ['A', 'A', 'B', 'B', 'A'],
 'key2': ['one', 'two', 'one', 'two', 'one'],
 'data1': [1, 2, 3, 4, 5],
 'data2': [10, 20, 30, 40, 50]
})
df2


key1 key2  data1  data2
0    A  one      1     10
1    A  two      2     20
2    B  one      3     30
3    B  two      4     40
4    A  one      5     50

In [232]:
groups = df2.groupby(df2.key1)
groups

In [234]:
groups.groups

{'A': [0, 1, 4], 'B': [2, 3]}

In [237]:
groups.sum()

C:\Users\user\AppData\Local\Temp\ipykernel_4152\1171057664.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  groups.sum()


data1  data2
key1              
A         8     80
B         7     70

In [238]:
df2.data1.groupby(df2.key1).sum()

key1
A    8
B    7
Name: data1, dtype: int64

In [240]:
df2.groupby(df2.key1)['data1'].sum()

key1
A    8
B    7
Name: data1, dtype: int64

In [241]:
df2.groupby(df2.key1).sum()['data1']

C:\Users\user\AppData\Local\Temp\ipykernel_4152\37063340.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df2.groupby(df2.key1).sum()['data1']


key1
A    8
B    7
Name: data1, dtype: int64